export interface IData {
    num: string;
    brand: string;
    model: string;
    year: string;
    body: string;
    color: string;
    transmission: string;
    fuel: string;
    favorite: boolean;
}

export const data: IData[] = [
    {
        num: '1',
        brand: 'Audi',
        model: 'Audi A4 45 S line',
        year: '2021',
        body: 'Sedan',
        color: 'White',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: true,
    },
    {
        num: '2',
        brand: 'Audi',
        model: 'Audi A6',
        year: '2003',
        body: 'Sedan',
        color: 'Gray',
        transmission: 'Manual',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '3',
        brand: 'Audi',
        model: 'Audi A6',
        year: '2005',
        body: 'Sedan',
        color: 'Black',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '4',
        brand: 'Audi',
        model: 'Audi Q3',
        year: '2021',
        body: 'SUV',
        color: 'Blue',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: true,
    },
    {
        num: '5',
        brand: 'Audi',
        model: 'Audi Q5',
        year: '2014',
        body: 'SUV',
        color: 'Gray',
        transmission: 'Automatic',
        fuel: 'Diesel',
        favorite: false,
    },
    {
        num: '6',
        brand: 'Audi',
        model: 'Audi Q7',
        year: '2013',
        body: 'SUV',
        color: 'Blue',
        transmission: 'Automatic',
        fuel: 'Diesel',
        favorite: true,
    },
    {
        num: '7',
        brand: 'Audi',
        model: 'Audi Q7',
        year: '2015',
        body: 'SUV',
        color: 'White',
        transmission: 'Automatic',
        fuel: 'Diesel',
        favorite: false,
    },
    {
        num: '8',
        brand: 'Audi',
        model: 'Audi Q7',
        year: '2016',
        body: 'SUV',
        color: 'Black',
        transmission: 'Automatic',
        fuel: 'Diesel',
        favorite: false,
    },
    {
        num: '9',
        brand: 'Audi',
        model: 'Audi S5',
        year: '2010',
        body: 'Coupe',
        color: 'White',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '10',
        brand: 'Audi',
        model: 'Audi TT',
        year: '2004',
        body: 'Coupe',
        color: 'Red',
        transmission: 'Manual',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '11',
        brand: 'BMW',
        model: 'BMW 335 i',
        year: '2013',
        body: 'Sedan',
        color: 'Red',
        transmission: 'Manual',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '12',
        brand: 'BMW',
        model: 'BMW 428',
        year: '2016',
        body: 'Coupe',
        color: 'Red',
        transmission: 'Manual',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '13',
        brand: 'BMW',
        model: 'BMW 430 i',
        year: '2021',
        body: 'Coupe',
        color: 'Black',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '14',
        brand: 'BMW',
        model: 'BMW 430',
        year: '2018',
        body: 'Hatchback',
        color: 'Gray',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: true,
    },
    {
        num: '15',
        brand: 'BMW',
        model: 'BMW 530 i',
        year: '2003',
        body: 'Sedan',
        color: 'Gray',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '16',
        brand: 'BMW',
        model: 'BMW 640',
        year: '2019',
        body: 'Hatchback',
        color: 'Black',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '17',
        brand: 'BMW',
        model: 'BMW i3',
        year: '2014',
        body: 'Hatchback',
        color: 'White',
        transmission: 'Automatic',
        fuel: 'Electric',
        favorite: false,
    },
    {
        num: '18',
        brand: 'BMW',
        model: 'BMW i3',
        year: '2017',
        body: 'Hatchback',
        color: 'Blue',
        transmission: 'Automatic',
        fuel: 'Electric',
        favorite: false,
    },
    {
        num: '19',
        brand: 'BMW',
        model: 'BMW M4 CS',
        year: '2019',
        body: 'Coupe',
        color: 'Blue',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: true,
    },
    {
        num: '20',
        brand: 'BMW',
        model: 'BMW Z3 M',
        year: '2000',
        body: 'Coupe',
        color: 'Black',
        transmission: 'Manual',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '21',
        brand: 'Ford',
        model: 'Ford Edge ST',
        year: '2020',
        body: 'SUV',
        color: 'Blue',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '22',
        brand: 'Ford',
        model: 'Ford F-150 Lariat',
        year: '2018',
        body: 'Pickup Truck',
        color: 'Gray',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '23',
        brand: 'Ford',
        model: 'Ford F-250 XLT',
        year: '2017',
        body: 'Pickup Truck',
        color: 'Red',
        transmission: 'Automanual',
        fuel: 'Diesel',
        favorite: false,
    },
    {
        num: '24',
        brand: 'Ford',
        model: 'Ford F-450 Platinum',
        year: '2019',
        body: 'Pickup Truck',
        color: 'Gray',
        transmission: 'Automatic',
        fuel: 'Diesel',
        favorite: false,
    },
    {
        num: '25',
        brand: 'Ford',
        model: 'Ford Focus Electric',
        year: '2014',
        body: 'Hatchback',
        color: 'Gray',
        transmission: 'Automatic',
        fuel: 'Electric',
        favorite: false,
    },
    {
        num: '26',
        brand: 'Ford',
        model: 'Ford Focus RS Base',
        year: '2015',
        body: 'Hatchback',
        color: 'Blue',
        transmission: 'Manual',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '27',
        brand: 'Ford',
        model: 'Ford Focus RS Base',
        year: '2016',
        body: 'Hatchback',
        color: 'White',
        transmission: 'Manual',
        fuel: 'Gasoline',
        favorite: true,
    },
    {
        num: '28',
        brand: 'Ford',
        model: 'Ford Focus SE',
        year: '2013',
        body: 'Sedan',
        color: 'Gray',
        transmission: 'Manual',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '29',
        brand: 'Ford',
        model: 'Ford Mustang GT',
        year: '2021',
        body: 'Coupe',
        color: 'Black',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '30',
        brand: 'Ford',
        model: 'Ford Mustang Mach E',
        year: '2021',
        body: 'SUV',
        color: 'White',
        transmission: 'Automatic',
        fuel: 'Electric',
        favorite: true,
    },
    {
        num: '31',
        brand: 'Honda',
        model: 'Honda Civic LX',
        year: '2011',
        body: 'Sedan',
        color: 'Gray',
        transmission: 'Automanual',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '32',
        brand: 'Honda',
        model: 'Honda Civic Si',
        year: '2020',
        body: 'Coupe',
        color: 'White',
        transmission: 'Manual',
        fuel: 'Gasoline',
        favorite: true,
    },
    {
        num: '33',
        brand: 'Honda',
        model: 'Honda Civic Si',
        year: '2020',
        body: 'Hatchback',
        color: 'Black',
        transmission: 'Manual',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '34',
        brand: 'Honda',
        model: 'Honda Civic Sport',
        year: '2019',
        body: 'Hatchback',
        color: 'Red',
        transmission: 'Manual',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '35',
        brand: 'Honda',
        model: 'Honda Civic Type R',
        year: '2021',
        body: 'Hatchback',
        color: 'Blue',
        transmission: 'Manual',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '36',
        brand: 'Honda',
        model: 'Honda Passport Touring',
        year: '2019',
        body: 'SUV',
        color: 'Gray',
        transmission: 'Automanual',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '37',
        brand: 'Honda',
        model: 'Honda Ridgeline RTL',
        year: '2012',
        body: 'Pickup Truck',
        color: 'Red',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '38',
        brand: 'Honda',
        model: 'Honda Ridgeline RTL-E',
        year: '2018',
        body: 'Pickup Truck',
        color: 'Blue',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '39',
        brand: 'Honda',
        model: 'Honda Ridgeline RTL-E',
        year: '2019',
        body: 'Pickup Truck',
        color: 'White',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '40',
        brand: 'Honda',
        model: 'Honda Ridgeline RTL-E',
        year: '2020',
        body: 'Pickup Truck',
        color: 'Gray',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: true,
    },
    {
        num: '41',
        brand: 'Mercedes',
        model: 'Mercedes A 220',
        year: '2019',
        body: 'Sedan',
        color: 'Red',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '42',
        brand: 'Mercedes',
        model: 'Mercedes C 230',
        year: '2004',
        body: 'Sedan',
        color: 'Gray',
        transmission: 'Manual',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '43',
        brand: 'Mercedes',
        model: 'Mercedes CLA 250',
        year: '2019',
        body: 'Sedan',
        color: 'White',
        transmission: 'Automanual',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '44',
        brand: 'Mercedes',
        model: 'Mercedes E 320',
        year: '2002',
        body: 'Sedan',
        color: 'Gray',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '45',
        brand: 'Mercedes',
        model: 'Mercedes E 320',
        year: '2005',
        body: 'Sedan',
        color: 'Gray',
        transmission: 'Automatic',
        fuel: 'Diesel',
        favorite: false,
    },
    {
        num: '46',
        brand: 'Mercedes',
        model: 'Mercedes GL 320',
        year: '2008',
        body: 'SUV',
        color: 'Black',
        transmission: 'Automatic',
        fuel: 'Diesel',
        favorite: false,
    },
    {
        num: '47',
        brand: 'Mercedes',
        model: 'Mercedes GLA 250',
        year: '2021',
        body: 'SUV',
        color: 'Black',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '48',
        brand: 'Mercedes',
        model: 'Mercedes GLE 350',
        year: '2020',
        body: 'SUV',
        color: 'White',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: true,
    },
    {
        num: '49',
        brand: 'Mercedes',
        model: 'Mercedes S 550',
        year: '2015',
        body: 'Sedan',
        color: 'White',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '50',
        brand: 'Mercedes',
        model: 'Mercedes SLK 320',
        year: '2001',
        body: 'Coupe',
        color: 'Blue',
        transmission: 'Manual',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '51',
        brand: 'Porsche',
        model: 'Porsche 911 Carrera',
        year: '2020',
        body: 'Coupe',
        color: 'Gray',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: true,
    },
    {
        num: '52',
        brand: 'Porsche',
        model: 'Porsche 911',
        year: '2021',
        body: 'Coupe',
        color: 'Red',
        transmission: 'Automatic',
        fuel: 'Gasoline',
        favorite: false,
    },
    {
        num: '53',
        brand: 'Porsche',
        model: 'Porsche Cayenne',
        year: '2013',
        body: 'SUV',
        color: 'Blue',
        transmission: 'Automatic',
        fuel: 'Diesel',
        favorite: false,
    },
    {
        num: '54',
        brand: 'Porsche',
        model: 'Porsche Cayenne',
        year: '2014',
        body: 'SUV',
        color: 'White',
        transmission: 'Automatic',
        fuel: 'Diesel',
        favorite: false,
    },
    {
        num: '55',
        brand: 'Porsche',
        model: 'Porsche Cayenne',
        year: '2015',
        body: 'SUV',
        color: 'Black',
        transmission: 'Automatic',
        fuel: 'Diesel',
        favorite: false,
    },
    {
        num: '56',
        brand: 'Porsche',
        model: 'Porsche Cayenne',
        year: '2016',
        body: 'SUV',
        color: 'Black',
        transmission: 'Automatic',
        fuel: 'Diesel',
        favorite: false,
    },
    {
        num: '57',
        brand: 'Porsche',
        model: 'Porsche Taycan 4S',
        year: '2020',
        body: 'Hatchback',
        color: 'Red',
        transmission: 'Automatic',
        fuel: 'Electric',
        favorite: false,
    },
    {
        num: '58',
        brand: 'Porsche',
        model: 'Porsche Taycan 4S',
        year: '2020',
        body: 'Hatchback',
        color: 'Gray',
        transmission: 'Automatic',
        fuel: 'Electric',
        favorite: true,
    },
    {
        num: '59',
        brand: 'Porsche',
        model: 'Porsche Taycan 4S',
        year: '2021',
        body: 'Hatchback',
        color: 'Black',
        transmission: 'Automatic',
        fuel: 'Electric',
        favorite: false,
    },
    {
        num: '60',
        brand: 'Porsche',
        model: 'Porsche Taycan 4S',
        year: '2021',
        body: 'Hatchback',
        color: 'Blue',
        transmission: 'Automatic',
        fuel: 'Electric',
        favorite: false,
    },
];

export default data;
